version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus-data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - devnetwork
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1234
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - devnetwork
    restart: unless-stopped
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgre-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=admin
      - POSTGRES_DB=dms_db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin-data:/var/lib/pgadmin    
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb-storage:/data/db 
volumes:
  prometheus-storage:
  grafana-storage:
  postgre-storage:
  pgadmin-data:
  mongodb-storage:
networks:
  devnetwork:
    external: false
    driver: bridge